version: "3.7"

services:
  recommender:
    image: recommender:latest
    build:
      context: ./
    ports:
      - 5000:5000
    volumes:
      - .:/recommender
    entrypoint: [
        "jupyter", "lab", "--ip", "0.0.0.0", "--port", "5000", "--allow-root"
    ]